[workspace]

members = [
    "crates/prompt-generator",
    "crates/api-connector",
    "crates/guy",
    "crates/missy",
    "binaries/randomizer",
    "binaries/shia",
    "binaries/ia"
]

resolver = "2"